# Generated by Django 4.2.3 on 2023-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('phone', models.CharField(max_length=222)),
                ('desc', models.TextField(max_length=222)),
            ],
        ),
    ]
